version: '3.8'

services:
  container_name: payping
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: payping-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - payping-network

networks:
  payping-network:
    driver: bridge